language: objective-c
osx_image: xcode9.1
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "JWRefreshControlDemo.xcodeproj" -scheme "JWRefreshControl" -configuration Debug ONLY_ACTIVE_ARCH=NO build